/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ExpensesRouteRouteImport } from './routes/expenses/route'
import { Route as PayrollRouteRouteImport } from './routes/payroll/route'
import { Route as ProductionRouteRouteImport } from './routes/production/route'
import { Route as ReportsRouteRouteImport } from './routes/reports/route'
import { Route as StockRouteRouteImport } from './routes/stock/route'
import { Route as TeamRouteRouteImport } from './routes/team/route'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as AdminRolesPermissionsRouteImport } from './routes/admin/roles-permissions'
import { Route as AdminUtilisateursRouteImport } from './routes/admin/utilisateurs'
import { Route as ProductionIndexRouteImport } from './routes/production/index'
import { Route as ReportsCoutsRouteImport } from './routes/reports/couts'
import { Route as ReportsDepensesRouteImport } from './routes/reports/depenses'
import { Route as ReportsPaieRouteImport } from './routes/reports/paie'
import { Route as ReportsProductionRouteImport } from './routes/reports/production'
import { Route as ReportsProductiviteRouteImport } from './routes/reports/productivite'
import { Route as ReportsStockRouteImport } from './routes/reports/stock'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as TeamAffectationsRouteImport } from './routes/team/affectations'
import { Route as TeamOuvriersRouteImport } from './routes/team/ouvriers'
import { Route as TeamTravailRouteImport } from './routes/team/travail'
import { Route as ExpensesCategoriesIndexRouteImport } from './routes/expenses/categories/index'
import { Route as ExpensesDepensesRecurrentesIndexRouteImport } from './routes/expenses/depenses-recurrentes/index'
import { Route as ExpensesDepensesIndexRouteImport } from './routes/expenses/depenses/index'
import { Route as PayrollAvancesAvancesRouteImport } from './routes/payroll/avances/avances'
import { Route as PayrollBaremesBaremesRouteImport } from './routes/payroll/baremes/baremes'
import { Route as PayrollCalculMensuelCalculMensuelRouteImport } from './routes/payroll/calcul-mensuel/calcul-mensuel'
import { Route as PayrollCloturesCloturesRouteImport } from './routes/payroll/clotures/clotures'
import { Route as PayrollPrimesPrimesRouteImport } from './routes/payroll/primes/primes'
import { Route as PayrollRetenuesRetenuesRouteImport } from './routes/payroll/retenues/retenues'
import { Route as ProductionArticlesIndexRouteImport } from './routes/production/articles/index'
import { Route as ProductionAvancementIndexRouteImport } from './routes/production/avancement/index'
import { Route as ProductionLotsIndexRouteImport } from './routes/production/lots/index'
import { Route as StockAlertesIndexRouteImport } from './routes/stock/alertes/index'
import { Route as StockEntreesIndexRouteImport } from './routes/stock/entrees/index'
import { Route as StockInventaireIndexRouteImport } from './routes/stock/inventaire/index'
import { Route as StockMatieresIndexRouteImport } from './routes/stock/matieres/index'
import { Route as StockMatieresAjouterRouteImport } from './routes/stock/matieres/ajouter'
import { Route as StockMouvementsIndexRouteImport } from './routes/stock/mouvements/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRouteRoute = ExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRouteRoute = PayrollRouteRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRouteRoute = ProductionRouteRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRouteRoute = ReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRouteRoute = StockRouteRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRouteRoute = TeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesPermissionsRoute = AdminRolesPermissionsRouteImport.update({
  id: '/roles-permissions',
  path: '/roles-permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ReportsCoutsRoute = ReportsCoutsRouteImport.update({
  id: '/couts',
  path: '/couts',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsDepensesRoute = ReportsDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsPaieRoute = ReportsPaieRouteImport.update({
  id: '/paie',
  path: '/paie',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsProductionRoute = ReportsProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsProductiviteRoute = ReportsProductiviteRouteImport.update({
  id: '/productivite',
  path: '/productivite',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsStockRoute = ReportsStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StockRouteRoute,
} as any)
const TeamAffectationsRoute = TeamAffectationsRouteImport.update({
  id: '/affectations',
  path: '/affectations',
  getParentRoute: () => TeamRouteRoute,
} as any)
const TeamOuvriersRoute = TeamOuvriersRouteImport.update({
  id: '/ouvriers',
  path: '/ouvriers',
  getParentRoute: () => TeamRouteRoute,
} as any)
const TeamTravailRoute = TeamTravailRouteImport.update({
  id: '/travail',
  path: '/travail',
  getParentRoute: () => TeamRouteRoute,
} as any)
const ExpensesCategoriesIndexRoute = ExpensesCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesDepensesRecurrentesIndexRoute =
  ExpensesDepensesRecurrentesIndexRouteImport.update({
    id: '/depenses-recurrentes/',
    path: '/depenses-recurrentes/',
    getParentRoute: () => ExpensesRouteRoute,
  } as any)
const ExpensesDepensesIndexRoute = ExpensesDepensesIndexRouteImport.update({
  id: '/depenses/',
  path: '/depenses/',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const PayrollAvancesAvancesRoute = PayrollAvancesAvancesRouteImport.update({
  id: '/avances/avances',
  path: '/avances/avances',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollBaremesBaremesRoute = PayrollBaremesBaremesRouteImport.update({
  id: '/baremes/baremes',
  path: '/baremes/baremes',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollCalculMensuelCalculMensuelRoute =
  PayrollCalculMensuelCalculMensuelRouteImport.update({
    id: '/calcul-mensuel/calcul-mensuel',
    path: '/calcul-mensuel/calcul-mensuel',
    getParentRoute: () => PayrollRouteRoute,
  } as any)
const PayrollCloturesCloturesRoute = PayrollCloturesCloturesRouteImport.update({
  id: '/clotures/clotures',
  path: '/clotures/clotures',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollPrimesPrimesRoute = PayrollPrimesPrimesRouteImport.update({
  id: '/primes/primes',
  path: '/primes/primes',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollRetenuesRetenuesRoute = PayrollRetenuesRetenuesRouteImport.update({
  id: '/retenues/retenues',
  path: '/retenues/retenues',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const ProductionArticlesIndexRoute = ProductionArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ProductionAvancementIndexRoute =
  ProductionAvancementIndexRouteImport.update({
    id: '/avancement/',
    path: '/avancement/',
    getParentRoute: () => ProductionRouteRoute,
  } as any)
const ProductionLotsIndexRoute = ProductionLotsIndexRouteImport.update({
  id: '/lots/',
  path: '/lots/',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const StockAlertesIndexRoute = StockAlertesIndexRouteImport.update({
  id: '/alertes/',
  path: '/alertes/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockEntreesIndexRoute = StockEntreesIndexRouteImport.update({
  id: '/entrees/',
  path: '/entrees/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockInventaireIndexRoute = StockInventaireIndexRouteImport.update({
  id: '/inventaire/',
  path: '/inventaire/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockMatieresIndexRoute = StockMatieresIndexRouteImport.update({
  id: '/matieres/',
  path: '/matieres/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockMatieresAjouterRoute = StockMatieresAjouterRouteImport.update({
  id: '/matieres/ajouter',
  path: '/matieres/ajouter',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockMouvementsIndexRoute = StockMouvementsIndexRouteImport.update({
  id: '/mouvements/',
  path: '/mouvements/',
  getParentRoute: () => StockRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/payroll': typeof PayrollRouteRouteWithChildren
  '/production': typeof ProductionRouteRouteWithChildren
  '/reports': typeof ReportsRouteRouteWithChildren
  '/stock': typeof StockRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/roles-permissions': typeof AdminRolesPermissionsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/reports/couts': typeof ReportsCoutsRoute
  '/reports/depenses': typeof ReportsDepensesRoute
  '/reports/paie': typeof ReportsPaieRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/productivite': typeof ReportsProductiviteRoute
  '/reports/stock': typeof ReportsStockRoute
  '/team/affectations': typeof TeamAffectationsRoute
  '/team/ouvriers': typeof TeamOuvriersRoute
  '/team/travail': typeof TeamTravailRoute
  '/production/': typeof ProductionIndexRoute
  '/stock/': typeof StockIndexRoute
  '/payroll/avances/avances': typeof PayrollAvancesAvancesRoute
  '/payroll/baremes/baremes': typeof PayrollBaremesBaremesRoute
  '/payroll/calcul-mensuel/calcul-mensuel': typeof PayrollCalculMensuelCalculMensuelRoute
  '/payroll/clotures/clotures': typeof PayrollCloturesCloturesRoute
  '/payroll/primes/primes': typeof PayrollPrimesPrimesRoute
  '/payroll/retenues/retenues': typeof PayrollRetenuesRetenuesRoute
  '/stock/matieres/ajouter': typeof StockMatieresAjouterRoute
  '/expenses/categories/': typeof ExpensesCategoriesIndexRoute
  '/expenses/depenses-recurrentes/': typeof ExpensesDepensesRecurrentesIndexRoute
  '/expenses/depenses/': typeof ExpensesDepensesIndexRoute
  '/production/articles/': typeof ProductionArticlesIndexRoute
  '/production/avancement/': typeof ProductionAvancementIndexRoute
  '/production/lots/': typeof ProductionLotsIndexRoute
  '/stock/alertes/': typeof StockAlertesIndexRoute
  '/stock/entrees/': typeof StockEntreesIndexRoute
  '/stock/inventaire/': typeof StockInventaireIndexRoute
  '/stock/matieres/': typeof StockMatieresIndexRoute
  '/stock/mouvements/': typeof StockMouvementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/payroll': typeof PayrollRouteRouteWithChildren
  '/reports': typeof ReportsRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/roles-permissions': typeof AdminRolesPermissionsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/reports/couts': typeof ReportsCoutsRoute
  '/reports/depenses': typeof ReportsDepensesRoute
  '/reports/paie': typeof ReportsPaieRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/productivite': typeof ReportsProductiviteRoute
  '/reports/stock': typeof ReportsStockRoute
  '/team/affectations': typeof TeamAffectationsRoute
  '/team/ouvriers': typeof TeamOuvriersRoute
  '/team/travail': typeof TeamTravailRoute
  '/production': typeof ProductionIndexRoute
  '/stock': typeof StockIndexRoute
  '/payroll/avances/avances': typeof PayrollAvancesAvancesRoute
  '/payroll/baremes/baremes': typeof PayrollBaremesBaremesRoute
  '/payroll/calcul-mensuel/calcul-mensuel': typeof PayrollCalculMensuelCalculMensuelRoute
  '/payroll/clotures/clotures': typeof PayrollCloturesCloturesRoute
  '/payroll/primes/primes': typeof PayrollPrimesPrimesRoute
  '/payroll/retenues/retenues': typeof PayrollRetenuesRetenuesRoute
  '/stock/matieres/ajouter': typeof StockMatieresAjouterRoute
  '/expenses/categories': typeof ExpensesCategoriesIndexRoute
  '/expenses/depenses-recurrentes': typeof ExpensesDepensesRecurrentesIndexRoute
  '/expenses/depenses': typeof ExpensesDepensesIndexRoute
  '/production/articles': typeof ProductionArticlesIndexRoute
  '/production/avancement': typeof ProductionAvancementIndexRoute
  '/production/lots': typeof ProductionLotsIndexRoute
  '/stock/alertes': typeof StockAlertesIndexRoute
  '/stock/entrees': typeof StockEntreesIndexRoute
  '/stock/inventaire': typeof StockInventaireIndexRoute
  '/stock/matieres': typeof StockMatieresIndexRoute
  '/stock/mouvements': typeof StockMouvementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/payroll': typeof PayrollRouteRouteWithChildren
  '/production': typeof ProductionRouteRouteWithChildren
  '/reports': typeof ReportsRouteRouteWithChildren
  '/stock': typeof StockRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/roles-permissions': typeof AdminRolesPermissionsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/reports/couts': typeof ReportsCoutsRoute
  '/reports/depenses': typeof ReportsDepensesRoute
  '/reports/paie': typeof ReportsPaieRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/productivite': typeof ReportsProductiviteRoute
  '/reports/stock': typeof ReportsStockRoute
  '/team/affectations': typeof TeamAffectationsRoute
  '/team/ouvriers': typeof TeamOuvriersRoute
  '/team/travail': typeof TeamTravailRoute
  '/production/': typeof ProductionIndexRoute
  '/stock/': typeof StockIndexRoute
  '/payroll/avances/avances': typeof PayrollAvancesAvancesRoute
  '/payroll/baremes/baremes': typeof PayrollBaremesBaremesRoute
  '/payroll/calcul-mensuel/calcul-mensuel': typeof PayrollCalculMensuelCalculMensuelRoute
  '/payroll/clotures/clotures': typeof PayrollCloturesCloturesRoute
  '/payroll/primes/primes': typeof PayrollPrimesPrimesRoute
  '/payroll/retenues/retenues': typeof PayrollRetenuesRetenuesRoute
  '/stock/matieres/ajouter': typeof StockMatieresAjouterRoute
  '/expenses/categories/': typeof ExpensesCategoriesIndexRoute
  '/expenses/depenses-recurrentes/': typeof ExpensesDepensesRecurrentesIndexRoute
  '/expenses/depenses/': typeof ExpensesDepensesIndexRoute
  '/production/articles/': typeof ProductionArticlesIndexRoute
  '/production/avancement/': typeof ProductionAvancementIndexRoute
  '/production/lots/': typeof ProductionLotsIndexRoute
  '/stock/alertes/': typeof StockAlertesIndexRoute
  '/stock/entrees/': typeof StockEntreesIndexRoute
  '/stock/inventaire/': typeof StockInventaireIndexRoute
  '/stock/matieres/': typeof StockMatieresIndexRoute
  '/stock/mouvements/': typeof StockMouvementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/expenses'
    | '/payroll'
    | '/production'
    | '/reports'
    | '/stock'
    | '/team'
    | '/admin/audit'
    | '/admin/parametres'
    | '/admin/roles-permissions'
    | '/admin/utilisateurs'
    | '/reports/couts'
    | '/reports/depenses'
    | '/reports/paie'
    | '/reports/production'
    | '/reports/productivite'
    | '/reports/stock'
    | '/team/affectations'
    | '/team/ouvriers'
    | '/team/travail'
    | '/production/'
    | '/stock/'
    | '/payroll/avances/avances'
    | '/payroll/baremes/baremes'
    | '/payroll/calcul-mensuel/calcul-mensuel'
    | '/payroll/clotures/clotures'
    | '/payroll/primes/primes'
    | '/payroll/retenues/retenues'
    | '/stock/matieres/ajouter'
    | '/expenses/categories/'
    | '/expenses/depenses-recurrentes/'
    | '/expenses/depenses/'
    | '/production/articles/'
    | '/production/avancement/'
    | '/production/lots/'
    | '/stock/alertes/'
    | '/stock/entrees/'
    | '/stock/inventaire/'
    | '/stock/matieres/'
    | '/stock/mouvements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/expenses'
    | '/payroll'
    | '/reports'
    | '/team'
    | '/admin/audit'
    | '/admin/parametres'
    | '/admin/roles-permissions'
    | '/admin/utilisateurs'
    | '/reports/couts'
    | '/reports/depenses'
    | '/reports/paie'
    | '/reports/production'
    | '/reports/productivite'
    | '/reports/stock'
    | '/team/affectations'
    | '/team/ouvriers'
    | '/team/travail'
    | '/production'
    | '/stock'
    | '/payroll/avances/avances'
    | '/payroll/baremes/baremes'
    | '/payroll/calcul-mensuel/calcul-mensuel'
    | '/payroll/clotures/clotures'
    | '/payroll/primes/primes'
    | '/payroll/retenues/retenues'
    | '/stock/matieres/ajouter'
    | '/expenses/categories'
    | '/expenses/depenses-recurrentes'
    | '/expenses/depenses'
    | '/production/articles'
    | '/production/avancement'
    | '/production/lots'
    | '/stock/alertes'
    | '/stock/entrees'
    | '/stock/inventaire'
    | '/stock/matieres'
    | '/stock/mouvements'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/expenses'
    | '/payroll'
    | '/production'
    | '/reports'
    | '/stock'
    | '/team'
    | '/admin/audit'
    | '/admin/parametres'
    | '/admin/roles-permissions'
    | '/admin/utilisateurs'
    | '/reports/couts'
    | '/reports/depenses'
    | '/reports/paie'
    | '/reports/production'
    | '/reports/productivite'
    | '/reports/stock'
    | '/team/affectations'
    | '/team/ouvriers'
    | '/team/travail'
    | '/production/'
    | '/stock/'
    | '/payroll/avances/avances'
    | '/payroll/baremes/baremes'
    | '/payroll/calcul-mensuel/calcul-mensuel'
    | '/payroll/clotures/clotures'
    | '/payroll/primes/primes'
    | '/payroll/retenues/retenues'
    | '/stock/matieres/ajouter'
    | '/expenses/categories/'
    | '/expenses/depenses-recurrentes/'
    | '/expenses/depenses/'
    | '/production/articles/'
    | '/production/avancement/'
    | '/production/lots/'
    | '/stock/alertes/'
    | '/stock/entrees/'
    | '/stock/inventaire/'
    | '/stock/matieres/'
    | '/stock/mouvements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ExpensesRouteRoute: typeof ExpensesRouteRouteWithChildren
  PayrollRouteRoute: typeof PayrollRouteRouteWithChildren
  ProductionRouteRoute: typeof ProductionRouteRouteWithChildren
  ReportsRouteRoute: typeof ReportsRouteRouteWithChildren
  StockRouteRoute: typeof StockRouteRouteWithChildren
  TeamRouteRoute: typeof TeamRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles-permissions': {
      id: '/admin/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/admin/roles-permissions'
      preLoaderRoute: typeof AdminRolesPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/production/': {
      id: '/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/reports/couts': {
      id: '/reports/couts'
      path: '/couts'
      fullPath: '/reports/couts'
      preLoaderRoute: typeof ReportsCoutsRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/depenses': {
      id: '/reports/depenses'
      path: '/depenses'
      fullPath: '/reports/depenses'
      preLoaderRoute: typeof ReportsDepensesRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/paie': {
      id: '/reports/paie'
      path: '/paie'
      fullPath: '/reports/paie'
      preLoaderRoute: typeof ReportsPaieRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/production': {
      id: '/reports/production'
      path: '/production'
      fullPath: '/reports/production'
      preLoaderRoute: typeof ReportsProductionRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/productivite': {
      id: '/reports/productivite'
      path: '/productivite'
      fullPath: '/reports/productivite'
      preLoaderRoute: typeof ReportsProductiviteRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/stock': {
      id: '/reports/stock'
      path: '/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof ReportsStockRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/stock/': {
      id: '/stock/'
      path: '/'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/team/affectations': {
      id: '/team/affectations'
      path: '/affectations'
      fullPath: '/team/affectations'
      preLoaderRoute: typeof TeamAffectationsRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/team/ouvriers': {
      id: '/team/ouvriers'
      path: '/ouvriers'
      fullPath: '/team/ouvriers'
      preLoaderRoute: typeof TeamOuvriersRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/team/travail': {
      id: '/team/travail'
      path: '/travail'
      fullPath: '/team/travail'
      preLoaderRoute: typeof TeamTravailRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/expenses/categories/': {
      id: '/expenses/categories/'
      path: '/categories'
      fullPath: '/expenses/categories/'
      preLoaderRoute: typeof ExpensesCategoriesIndexRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/depenses-recurrentes/': {
      id: '/expenses/depenses-recurrentes/'
      path: '/depenses-recurrentes'
      fullPath: '/expenses/depenses-recurrentes/'
      preLoaderRoute: typeof ExpensesDepensesRecurrentesIndexRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/depenses/': {
      id: '/expenses/depenses/'
      path: '/depenses'
      fullPath: '/expenses/depenses/'
      preLoaderRoute: typeof ExpensesDepensesIndexRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/payroll/avances/avances': {
      id: '/payroll/avances/avances'
      path: '/avances/avances'
      fullPath: '/payroll/avances/avances'
      preLoaderRoute: typeof PayrollAvancesAvancesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/baremes/baremes': {
      id: '/payroll/baremes/baremes'
      path: '/baremes/baremes'
      fullPath: '/payroll/baremes/baremes'
      preLoaderRoute: typeof PayrollBaremesBaremesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/calcul-mensuel/calcul-mensuel': {
      id: '/payroll/calcul-mensuel/calcul-mensuel'
      path: '/calcul-mensuel/calcul-mensuel'
      fullPath: '/payroll/calcul-mensuel/calcul-mensuel'
      preLoaderRoute: typeof PayrollCalculMensuelCalculMensuelRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/clotures/clotures': {
      id: '/payroll/clotures/clotures'
      path: '/clotures/clotures'
      fullPath: '/payroll/clotures/clotures'
      preLoaderRoute: typeof PayrollCloturesCloturesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/primes/primes': {
      id: '/payroll/primes/primes'
      path: '/primes/primes'
      fullPath: '/payroll/primes/primes'
      preLoaderRoute: typeof PayrollPrimesPrimesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/retenues/retenues': {
      id: '/payroll/retenues/retenues'
      path: '/retenues/retenues'
      fullPath: '/payroll/retenues/retenues'
      preLoaderRoute: typeof PayrollRetenuesRetenuesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/production/articles/': {
      id: '/production/articles/'
      path: '/articles'
      fullPath: '/production/articles/'
      preLoaderRoute: typeof ProductionArticlesIndexRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/production/avancement/': {
      id: '/production/avancement/'
      path: '/avancement'
      fullPath: '/production/avancement/'
      preLoaderRoute: typeof ProductionAvancementIndexRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/production/lots/': {
      id: '/production/lots/'
      path: '/lots'
      fullPath: '/production/lots/'
      preLoaderRoute: typeof ProductionLotsIndexRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/stock/alertes/': {
      id: '/stock/alertes/'
      path: '/alertes'
      fullPath: '/stock/alertes/'
      preLoaderRoute: typeof StockAlertesIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/entrees/': {
      id: '/stock/entrees/'
      path: '/entrees'
      fullPath: '/stock/entrees/'
      preLoaderRoute: typeof StockEntreesIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/inventaire/': {
      id: '/stock/inventaire/'
      path: '/inventaire'
      fullPath: '/stock/inventaire/'
      preLoaderRoute: typeof StockInventaireIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/matieres/': {
      id: '/stock/matieres/'
      path: '/matieres'
      fullPath: '/stock/matieres/'
      preLoaderRoute: typeof StockMatieresIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/matieres/ajouter': {
      id: '/stock/matieres/ajouter'
      path: '/matieres/ajouter'
      fullPath: '/stock/matieres/ajouter'
      preLoaderRoute: typeof StockMatieresAjouterRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/mouvements/': {
      id: '/stock/mouvements/'
      path: '/mouvements'
      fullPath: '/stock/mouvements/'
      preLoaderRoute: typeof StockMouvementsIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminRolesPermissionsRoute: typeof AdminRolesPermissionsRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminRolesPermissionsRoute: AdminRolesPermissionsRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ExpensesRouteRouteChildren {
  ExpensesCategoriesIndexRoute: typeof ExpensesCategoriesIndexRoute
  ExpensesDepensesRecurrentesIndexRoute: typeof ExpensesDepensesRecurrentesIndexRoute
  ExpensesDepensesIndexRoute: typeof ExpensesDepensesIndexRoute
}

const ExpensesRouteRouteChildren: ExpensesRouteRouteChildren = {
  ExpensesCategoriesIndexRoute: ExpensesCategoriesIndexRoute,
  ExpensesDepensesRecurrentesIndexRoute: ExpensesDepensesRecurrentesIndexRoute,
  ExpensesDepensesIndexRoute: ExpensesDepensesIndexRoute,
}

const ExpensesRouteRouteWithChildren = ExpensesRouteRoute._addFileChildren(
  ExpensesRouteRouteChildren,
)

interface PayrollRouteRouteChildren {
  PayrollAvancesAvancesRoute: typeof PayrollAvancesAvancesRoute
  PayrollBaremesBaremesRoute: typeof PayrollBaremesBaremesRoute
  PayrollCalculMensuelCalculMensuelRoute: typeof PayrollCalculMensuelCalculMensuelRoute
  PayrollCloturesCloturesRoute: typeof PayrollCloturesCloturesRoute
  PayrollPrimesPrimesRoute: typeof PayrollPrimesPrimesRoute
  PayrollRetenuesRetenuesRoute: typeof PayrollRetenuesRetenuesRoute
}

const PayrollRouteRouteChildren: PayrollRouteRouteChildren = {
  PayrollAvancesAvancesRoute: PayrollAvancesAvancesRoute,
  PayrollBaremesBaremesRoute: PayrollBaremesBaremesRoute,
  PayrollCalculMensuelCalculMensuelRoute:
    PayrollCalculMensuelCalculMensuelRoute,
  PayrollCloturesCloturesRoute: PayrollCloturesCloturesRoute,
  PayrollPrimesPrimesRoute: PayrollPrimesPrimesRoute,
  PayrollRetenuesRetenuesRoute: PayrollRetenuesRetenuesRoute,
}

const PayrollRouteRouteWithChildren = PayrollRouteRoute._addFileChildren(
  PayrollRouteRouteChildren,
)

interface ProductionRouteRouteChildren {
  ProductionIndexRoute: typeof ProductionIndexRoute
  ProductionArticlesIndexRoute: typeof ProductionArticlesIndexRoute
  ProductionAvancementIndexRoute: typeof ProductionAvancementIndexRoute
  ProductionLotsIndexRoute: typeof ProductionLotsIndexRoute
}

const ProductionRouteRouteChildren: ProductionRouteRouteChildren = {
  ProductionIndexRoute: ProductionIndexRoute,
  ProductionArticlesIndexRoute: ProductionArticlesIndexRoute,
  ProductionAvancementIndexRoute: ProductionAvancementIndexRoute,
  ProductionLotsIndexRoute: ProductionLotsIndexRoute,
}

const ProductionRouteRouteWithChildren = ProductionRouteRoute._addFileChildren(
  ProductionRouteRouteChildren,
)

interface ReportsRouteRouteChildren {
  ReportsCoutsRoute: typeof ReportsCoutsRoute
  ReportsDepensesRoute: typeof ReportsDepensesRoute
  ReportsPaieRoute: typeof ReportsPaieRoute
  ReportsProductionRoute: typeof ReportsProductionRoute
  ReportsProductiviteRoute: typeof ReportsProductiviteRoute
  ReportsStockRoute: typeof ReportsStockRoute
}

const ReportsRouteRouteChildren: ReportsRouteRouteChildren = {
  ReportsCoutsRoute: ReportsCoutsRoute,
  ReportsDepensesRoute: ReportsDepensesRoute,
  ReportsPaieRoute: ReportsPaieRoute,
  ReportsProductionRoute: ReportsProductionRoute,
  ReportsProductiviteRoute: ReportsProductiviteRoute,
  ReportsStockRoute: ReportsStockRoute,
}

const ReportsRouteRouteWithChildren = ReportsRouteRoute._addFileChildren(
  ReportsRouteRouteChildren,
)

interface StockRouteRouteChildren {
  StockIndexRoute: typeof StockIndexRoute
  StockMatieresAjouterRoute: typeof StockMatieresAjouterRoute
  StockAlertesIndexRoute: typeof StockAlertesIndexRoute
  StockEntreesIndexRoute: typeof StockEntreesIndexRoute
  StockInventaireIndexRoute: typeof StockInventaireIndexRoute
  StockMatieresIndexRoute: typeof StockMatieresIndexRoute
  StockMouvementsIndexRoute: typeof StockMouvementsIndexRoute
}

const StockRouteRouteChildren: StockRouteRouteChildren = {
  StockIndexRoute: StockIndexRoute,
  StockMatieresAjouterRoute: StockMatieresAjouterRoute,
  StockAlertesIndexRoute: StockAlertesIndexRoute,
  StockEntreesIndexRoute: StockEntreesIndexRoute,
  StockInventaireIndexRoute: StockInventaireIndexRoute,
  StockMatieresIndexRoute: StockMatieresIndexRoute,
  StockMouvementsIndexRoute: StockMouvementsIndexRoute,
}

const StockRouteRouteWithChildren = StockRouteRoute._addFileChildren(
  StockRouteRouteChildren,
)

interface TeamRouteRouteChildren {
  TeamAffectationsRoute: typeof TeamAffectationsRoute
  TeamOuvriersRoute: typeof TeamOuvriersRoute
  TeamTravailRoute: typeof TeamTravailRoute
}

const TeamRouteRouteChildren: TeamRouteRouteChildren = {
  TeamAffectationsRoute: TeamAffectationsRoute,
  TeamOuvriersRoute: TeamOuvriersRoute,
  TeamTravailRoute: TeamTravailRoute,
}

const TeamRouteRouteWithChildren = TeamRouteRoute._addFileChildren(
  TeamRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ExpensesRouteRoute: ExpensesRouteRouteWithChildren,
  PayrollRouteRoute: PayrollRouteRouteWithChildren,
  ProductionRouteRoute: ProductionRouteRouteWithChildren,
  ReportsRouteRoute: ReportsRouteRouteWithChildren,
  StockRouteRoute: StockRouteRouteWithChildren,
  TeamRouteRoute: TeamRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
