/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ExpensesRouteRouteImport } from './routes/expenses/route'
import { Route as PayrollRouteRouteImport } from './routes/payroll/route'
import { Route as ProductionRouteRouteImport } from './routes/production/route'
import { Route as ReportsRouteRouteImport } from './routes/reports/route'
import { Route as StockRouteRouteImport } from './routes/stock/route'
import { Route as TeamRouteRouteImport } from './routes/team/route'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as AdminRolesPermissionsRouteImport } from './routes/admin/roles-permissions'
import { Route as AdminUtilisateursRouteImport } from './routes/admin/utilisateurs'
import { Route as ExpensesCategoriesRouteImport } from './routes/expenses/categories'
import { Route as ExpensesDepensesRouteImport } from './routes/expenses/depenses'
import { Route as ExpensesDepensesRecurrentesRouteImport } from './routes/expenses/depenses-recurrentes'
import { Route as PayrollIndexRouteImport } from './routes/payroll/index'
import { Route as PayrollAvancesRouteImport } from './routes/payroll/avances'
import { Route as PayrollBaremesRouteImport } from './routes/payroll/baremes'
import { Route as PayrollCalculMensuelRouteImport } from './routes/payroll/calcul-mensuel'
import { Route as PayrollCloturesRouteImport } from './routes/payroll/clotures'
import { Route as PayrollFicheDePaieRouteImport } from './routes/payroll/fiche-de-paie'
import { Route as PayrollPrimesRouteImport } from './routes/payroll/primes'
import { Route as PayrollRetenuesRouteImport } from './routes/payroll/retenues'
import { Route as ProductionIndexRouteImport } from './routes/production/index'
import { Route as ProductionArticlesRouteImport } from './routes/production/articles'
import { Route as ProductionAvancementRouteImport } from './routes/production/avancement'
import { Route as ProductionConsommationRouteImport } from './routes/production/consommation'
import { Route as ProductionLotsRouteImport } from './routes/production/lots'
import { Route as ProductionOperationsRouteImport } from './routes/production/operations'
import { Route as ProductionRejetsRouteImport } from './routes/production/rejets'
import { Route as ReportsCoutsRouteImport } from './routes/reports/couts'
import { Route as ReportsDepensesRouteImport } from './routes/reports/depenses'
import { Route as ReportsPaieRouteImport } from './routes/reports/paie'
import { Route as ReportsProductionRouteImport } from './routes/reports/production'
import { Route as ReportsProductiviteRouteImport } from './routes/reports/productivite'
import { Route as ReportsStockRouteImport } from './routes/reports/stock'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as StockRetoursRouteImport } from './routes/stock/retours'
import { Route as StockRouleauxLotsRouteImport } from './routes/stock/rouleaux-lots'
import { Route as StockSortiesRouteImport } from './routes/stock/sorties'
import { Route as StockValorisationRouteImport } from './routes/stock/valorisation'
import { Route as TeamAffectationsRouteImport } from './routes/team/affectations'
import { Route as TeamOuvriersRouteImport } from './routes/team/ouvriers'
import { Route as TeamTravailRouteImport } from './routes/team/travail'
import { Route as StockAlertesIndexRouteImport } from './routes/stock/alertes/index'
import { Route as StockEntreesIndexRouteImport } from './routes/stock/entrees/index'
import { Route as StockInventaireIndexRouteImport } from './routes/stock/inventaire/index'
import { Route as StockMatieresIndexRouteImport } from './routes/stock/matieres/index'
import { Route as StockMatieresAjouterRouteImport } from './routes/stock/matieres/ajouter'
import { Route as StockMouvementsIndexRouteImport } from './routes/stock/mouvements/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRouteRoute = ExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRouteRoute = PayrollRouteRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRouteRoute = ProductionRouteRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRouteRoute = ReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRouteRoute = StockRouteRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRouteRoute = TeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesPermissionsRoute = AdminRolesPermissionsRouteImport.update({
  id: '/roles-permissions',
  path: '/roles-permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ExpensesCategoriesRoute = ExpensesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesDepensesRoute = ExpensesDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesDepensesRecurrentesRoute =
  ExpensesDepensesRecurrentesRouteImport.update({
    id: '/depenses-recurrentes',
    path: '/depenses-recurrentes',
    getParentRoute: () => ExpensesRouteRoute,
  } as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollAvancesRoute = PayrollAvancesRouteImport.update({
  id: '/avances',
  path: '/avances',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollBaremesRoute = PayrollBaremesRouteImport.update({
  id: '/baremes',
  path: '/baremes',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollCalculMensuelRoute = PayrollCalculMensuelRouteImport.update({
  id: '/calcul-mensuel',
  path: '/calcul-mensuel',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollCloturesRoute = PayrollCloturesRouteImport.update({
  id: '/clotures',
  path: '/clotures',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollFicheDePaieRoute = PayrollFicheDePaieRouteImport.update({
  id: '/fiche-de-paie',
  path: '/fiche-de-paie',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollPrimesRoute = PayrollPrimesRouteImport.update({
  id: '/primes',
  path: '/primes',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const PayrollRetenuesRoute = PayrollRetenuesRouteImport.update({
  id: '/retenues',
  path: '/retenues',
  getParentRoute: () => PayrollRouteRoute,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ProductionArticlesRoute = ProductionArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ProductionAvancementRoute = ProductionAvancementRouteImport.update({
  id: '/avancement',
  path: '/avancement',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ProductionConsommationRoute = ProductionConsommationRouteImport.update({
  id: '/consommation',
  path: '/consommation',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ProductionLotsRoute = ProductionLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ProductionOperationsRoute = ProductionOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ProductionRejetsRoute = ProductionRejetsRouteImport.update({
  id: '/rejets',
  path: '/rejets',
  getParentRoute: () => ProductionRouteRoute,
} as any)
const ReportsCoutsRoute = ReportsCoutsRouteImport.update({
  id: '/couts',
  path: '/couts',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsDepensesRoute = ReportsDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsPaieRoute = ReportsPaieRouteImport.update({
  id: '/paie',
  path: '/paie',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsProductionRoute = ReportsProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsProductiviteRoute = ReportsProductiviteRouteImport.update({
  id: '/productivite',
  path: '/productivite',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsStockRoute = ReportsStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockRetoursRoute = StockRetoursRouteImport.update({
  id: '/retours',
  path: '/retours',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockRouleauxLotsRoute = StockRouleauxLotsRouteImport.update({
  id: '/rouleaux-lots',
  path: '/rouleaux-lots',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockSortiesRoute = StockSortiesRouteImport.update({
  id: '/sorties',
  path: '/sorties',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockValorisationRoute = StockValorisationRouteImport.update({
  id: '/valorisation',
  path: '/valorisation',
  getParentRoute: () => StockRouteRoute,
} as any)
const TeamAffectationsRoute = TeamAffectationsRouteImport.update({
  id: '/affectations',
  path: '/affectations',
  getParentRoute: () => TeamRouteRoute,
} as any)
const TeamOuvriersRoute = TeamOuvriersRouteImport.update({
  id: '/ouvriers',
  path: '/ouvriers',
  getParentRoute: () => TeamRouteRoute,
} as any)
const TeamTravailRoute = TeamTravailRouteImport.update({
  id: '/travail',
  path: '/travail',
  getParentRoute: () => TeamRouteRoute,
} as any)
const StockAlertesIndexRoute = StockAlertesIndexRouteImport.update({
  id: '/alertes/',
  path: '/alertes/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockEntreesIndexRoute = StockEntreesIndexRouteImport.update({
  id: '/entrees/',
  path: '/entrees/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockInventaireIndexRoute = StockInventaireIndexRouteImport.update({
  id: '/inventaire/',
  path: '/inventaire/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockMatieresIndexRoute = StockMatieresIndexRouteImport.update({
  id: '/matieres/',
  path: '/matieres/',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockMatieresAjouterRoute = StockMatieresAjouterRouteImport.update({
  id: '/matieres/ajouter',
  path: '/matieres/ajouter',
  getParentRoute: () => StockRouteRoute,
} as any)
const StockMouvementsIndexRoute = StockMouvementsIndexRouteImport.update({
  id: '/mouvements/',
  path: '/mouvements/',
  getParentRoute: () => StockRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/payroll': typeof PayrollRouteRouteWithChildren
  '/production': typeof ProductionRouteRouteWithChildren
  '/reports': typeof ReportsRouteRouteWithChildren
  '/stock': typeof StockRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/roles-permissions': typeof AdminRolesPermissionsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/depenses': typeof ExpensesDepensesRoute
  '/expenses/depenses-recurrentes': typeof ExpensesDepensesRecurrentesRoute
  '/payroll/avances': typeof PayrollAvancesRoute
  '/payroll/baremes': typeof PayrollBaremesRoute
  '/payroll/calcul-mensuel': typeof PayrollCalculMensuelRoute
  '/payroll/clotures': typeof PayrollCloturesRoute
  '/payroll/fiche-de-paie': typeof PayrollFicheDePaieRoute
  '/payroll/primes': typeof PayrollPrimesRoute
  '/payroll/retenues': typeof PayrollRetenuesRoute
  '/production/articles': typeof ProductionArticlesRoute
  '/production/avancement': typeof ProductionAvancementRoute
  '/production/consommation': typeof ProductionConsommationRoute
  '/production/lots': typeof ProductionLotsRoute
  '/production/operations': typeof ProductionOperationsRoute
  '/production/rejets': typeof ProductionRejetsRoute
  '/reports/couts': typeof ReportsCoutsRoute
  '/reports/depenses': typeof ReportsDepensesRoute
  '/reports/paie': typeof ReportsPaieRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/productivite': typeof ReportsProductiviteRoute
  '/reports/stock': typeof ReportsStockRoute
  '/stock/retours': typeof StockRetoursRoute
  '/stock/rouleaux-lots': typeof StockRouleauxLotsRoute
  '/stock/sorties': typeof StockSortiesRoute
  '/stock/valorisation': typeof StockValorisationRoute
  '/team/affectations': typeof TeamAffectationsRoute
  '/team/ouvriers': typeof TeamOuvriersRoute
  '/team/travail': typeof TeamTravailRoute
  '/payroll/': typeof PayrollIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/stock/': typeof StockIndexRoute
  '/stock/matieres/ajouter': typeof StockMatieresAjouterRoute
  '/stock/alertes/': typeof StockAlertesIndexRoute
  '/stock/entrees/': typeof StockEntreesIndexRoute
  '/stock/inventaire/': typeof StockInventaireIndexRoute
  '/stock/matieres/': typeof StockMatieresIndexRoute
  '/stock/mouvements/': typeof StockMouvementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/reports': typeof ReportsRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/roles-permissions': typeof AdminRolesPermissionsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/depenses': typeof ExpensesDepensesRoute
  '/expenses/depenses-recurrentes': typeof ExpensesDepensesRecurrentesRoute
  '/payroll/avances': typeof PayrollAvancesRoute
  '/payroll/baremes': typeof PayrollBaremesRoute
  '/payroll/calcul-mensuel': typeof PayrollCalculMensuelRoute
  '/payroll/clotures': typeof PayrollCloturesRoute
  '/payroll/fiche-de-paie': typeof PayrollFicheDePaieRoute
  '/payroll/primes': typeof PayrollPrimesRoute
  '/payroll/retenues': typeof PayrollRetenuesRoute
  '/production/articles': typeof ProductionArticlesRoute
  '/production/avancement': typeof ProductionAvancementRoute
  '/production/consommation': typeof ProductionConsommationRoute
  '/production/lots': typeof ProductionLotsRoute
  '/production/operations': typeof ProductionOperationsRoute
  '/production/rejets': typeof ProductionRejetsRoute
  '/reports/couts': typeof ReportsCoutsRoute
  '/reports/depenses': typeof ReportsDepensesRoute
  '/reports/paie': typeof ReportsPaieRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/productivite': typeof ReportsProductiviteRoute
  '/reports/stock': typeof ReportsStockRoute
  '/stock/retours': typeof StockRetoursRoute
  '/stock/rouleaux-lots': typeof StockRouleauxLotsRoute
  '/stock/sorties': typeof StockSortiesRoute
  '/stock/valorisation': typeof StockValorisationRoute
  '/team/affectations': typeof TeamAffectationsRoute
  '/team/ouvriers': typeof TeamOuvriersRoute
  '/team/travail': typeof TeamTravailRoute
  '/payroll': typeof PayrollIndexRoute
  '/production': typeof ProductionIndexRoute
  '/stock': typeof StockIndexRoute
  '/stock/matieres/ajouter': typeof StockMatieresAjouterRoute
  '/stock/alertes': typeof StockAlertesIndexRoute
  '/stock/entrees': typeof StockEntreesIndexRoute
  '/stock/inventaire': typeof StockInventaireIndexRoute
  '/stock/matieres': typeof StockMatieresIndexRoute
  '/stock/mouvements': typeof StockMouvementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/payroll': typeof PayrollRouteRouteWithChildren
  '/production': typeof ProductionRouteRouteWithChildren
  '/reports': typeof ReportsRouteRouteWithChildren
  '/stock': typeof StockRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/roles-permissions': typeof AdminRolesPermissionsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/depenses': typeof ExpensesDepensesRoute
  '/expenses/depenses-recurrentes': typeof ExpensesDepensesRecurrentesRoute
  '/payroll/avances': typeof PayrollAvancesRoute
  '/payroll/baremes': typeof PayrollBaremesRoute
  '/payroll/calcul-mensuel': typeof PayrollCalculMensuelRoute
  '/payroll/clotures': typeof PayrollCloturesRoute
  '/payroll/fiche-de-paie': typeof PayrollFicheDePaieRoute
  '/payroll/primes': typeof PayrollPrimesRoute
  '/payroll/retenues': typeof PayrollRetenuesRoute
  '/production/articles': typeof ProductionArticlesRoute
  '/production/avancement': typeof ProductionAvancementRoute
  '/production/consommation': typeof ProductionConsommationRoute
  '/production/lots': typeof ProductionLotsRoute
  '/production/operations': typeof ProductionOperationsRoute
  '/production/rejets': typeof ProductionRejetsRoute
  '/reports/couts': typeof ReportsCoutsRoute
  '/reports/depenses': typeof ReportsDepensesRoute
  '/reports/paie': typeof ReportsPaieRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/productivite': typeof ReportsProductiviteRoute
  '/reports/stock': typeof ReportsStockRoute
  '/stock/retours': typeof StockRetoursRoute
  '/stock/rouleaux-lots': typeof StockRouleauxLotsRoute
  '/stock/sorties': typeof StockSortiesRoute
  '/stock/valorisation': typeof StockValorisationRoute
  '/team/affectations': typeof TeamAffectationsRoute
  '/team/ouvriers': typeof TeamOuvriersRoute
  '/team/travail': typeof TeamTravailRoute
  '/payroll/': typeof PayrollIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/stock/': typeof StockIndexRoute
  '/stock/matieres/ajouter': typeof StockMatieresAjouterRoute
  '/stock/alertes/': typeof StockAlertesIndexRoute
  '/stock/entrees/': typeof StockEntreesIndexRoute
  '/stock/inventaire/': typeof StockInventaireIndexRoute
  '/stock/matieres/': typeof StockMatieresIndexRoute
  '/stock/mouvements/': typeof StockMouvementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/expenses'
    | '/payroll'
    | '/production'
    | '/reports'
    | '/stock'
    | '/team'
    | '/admin/audit'
    | '/admin/parametres'
    | '/admin/roles-permissions'
    | '/admin/utilisateurs'
    | '/expenses/categories'
    | '/expenses/depenses'
    | '/expenses/depenses-recurrentes'
    | '/payroll/avances'
    | '/payroll/baremes'
    | '/payroll/calcul-mensuel'
    | '/payroll/clotures'
    | '/payroll/fiche-de-paie'
    | '/payroll/primes'
    | '/payroll/retenues'
    | '/production/articles'
    | '/production/avancement'
    | '/production/consommation'
    | '/production/lots'
    | '/production/operations'
    | '/production/rejets'
    | '/reports/couts'
    | '/reports/depenses'
    | '/reports/paie'
    | '/reports/production'
    | '/reports/productivite'
    | '/reports/stock'
    | '/stock/retours'
    | '/stock/rouleaux-lots'
    | '/stock/sorties'
    | '/stock/valorisation'
    | '/team/affectations'
    | '/team/ouvriers'
    | '/team/travail'
    | '/payroll/'
    | '/production/'
    | '/stock/'
    | '/stock/matieres/ajouter'
    | '/stock/alertes/'
    | '/stock/entrees/'
    | '/stock/inventaire/'
    | '/stock/matieres/'
    | '/stock/mouvements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/expenses'
    | '/reports'
    | '/team'
    | '/admin/audit'
    | '/admin/parametres'
    | '/admin/roles-permissions'
    | '/admin/utilisateurs'
    | '/expenses/categories'
    | '/expenses/depenses'
    | '/expenses/depenses-recurrentes'
    | '/payroll/avances'
    | '/payroll/baremes'
    | '/payroll/calcul-mensuel'
    | '/payroll/clotures'
    | '/payroll/fiche-de-paie'
    | '/payroll/primes'
    | '/payroll/retenues'
    | '/production/articles'
    | '/production/avancement'
    | '/production/consommation'
    | '/production/lots'
    | '/production/operations'
    | '/production/rejets'
    | '/reports/couts'
    | '/reports/depenses'
    | '/reports/paie'
    | '/reports/production'
    | '/reports/productivite'
    | '/reports/stock'
    | '/stock/retours'
    | '/stock/rouleaux-lots'
    | '/stock/sorties'
    | '/stock/valorisation'
    | '/team/affectations'
    | '/team/ouvriers'
    | '/team/travail'
    | '/payroll'
    | '/production'
    | '/stock'
    | '/stock/matieres/ajouter'
    | '/stock/alertes'
    | '/stock/entrees'
    | '/stock/inventaire'
    | '/stock/matieres'
    | '/stock/mouvements'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/expenses'
    | '/payroll'
    | '/production'
    | '/reports'
    | '/stock'
    | '/team'
    | '/admin/audit'
    | '/admin/parametres'
    | '/admin/roles-permissions'
    | '/admin/utilisateurs'
    | '/expenses/categories'
    | '/expenses/depenses'
    | '/expenses/depenses-recurrentes'
    | '/payroll/avances'
    | '/payroll/baremes'
    | '/payroll/calcul-mensuel'
    | '/payroll/clotures'
    | '/payroll/fiche-de-paie'
    | '/payroll/primes'
    | '/payroll/retenues'
    | '/production/articles'
    | '/production/avancement'
    | '/production/consommation'
    | '/production/lots'
    | '/production/operations'
    | '/production/rejets'
    | '/reports/couts'
    | '/reports/depenses'
    | '/reports/paie'
    | '/reports/production'
    | '/reports/productivite'
    | '/reports/stock'
    | '/stock/retours'
    | '/stock/rouleaux-lots'
    | '/stock/sorties'
    | '/stock/valorisation'
    | '/team/affectations'
    | '/team/ouvriers'
    | '/team/travail'
    | '/payroll/'
    | '/production/'
    | '/stock/'
    | '/stock/matieres/ajouter'
    | '/stock/alertes/'
    | '/stock/entrees/'
    | '/stock/inventaire/'
    | '/stock/matieres/'
    | '/stock/mouvements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ExpensesRouteRoute: typeof ExpensesRouteRouteWithChildren
  PayrollRouteRoute: typeof PayrollRouteRouteWithChildren
  ProductionRouteRoute: typeof ProductionRouteRouteWithChildren
  ReportsRouteRoute: typeof ReportsRouteRouteWithChildren
  StockRouteRoute: typeof StockRouteRouteWithChildren
  TeamRouteRoute: typeof TeamRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles-permissions': {
      id: '/admin/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/admin/roles-permissions'
      preLoaderRoute: typeof AdminRolesPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/expenses/categories': {
      id: '/expenses/categories'
      path: '/categories'
      fullPath: '/expenses/categories'
      preLoaderRoute: typeof ExpensesCategoriesRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/depenses': {
      id: '/expenses/depenses'
      path: '/depenses'
      fullPath: '/expenses/depenses'
      preLoaderRoute: typeof ExpensesDepensesRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/depenses-recurrentes': {
      id: '/expenses/depenses-recurrentes'
      path: '/depenses-recurrentes'
      fullPath: '/expenses/depenses-recurrentes'
      preLoaderRoute: typeof ExpensesDepensesRecurrentesRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/avances': {
      id: '/payroll/avances'
      path: '/avances'
      fullPath: '/payroll/avances'
      preLoaderRoute: typeof PayrollAvancesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/baremes': {
      id: '/payroll/baremes'
      path: '/baremes'
      fullPath: '/payroll/baremes'
      preLoaderRoute: typeof PayrollBaremesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/calcul-mensuel': {
      id: '/payroll/calcul-mensuel'
      path: '/calcul-mensuel'
      fullPath: '/payroll/calcul-mensuel'
      preLoaderRoute: typeof PayrollCalculMensuelRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/clotures': {
      id: '/payroll/clotures'
      path: '/clotures'
      fullPath: '/payroll/clotures'
      preLoaderRoute: typeof PayrollCloturesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/fiche-de-paie': {
      id: '/payroll/fiche-de-paie'
      path: '/fiche-de-paie'
      fullPath: '/payroll/fiche-de-paie'
      preLoaderRoute: typeof PayrollFicheDePaieRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/primes': {
      id: '/payroll/primes'
      path: '/primes'
      fullPath: '/payroll/primes'
      preLoaderRoute: typeof PayrollPrimesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/payroll/retenues': {
      id: '/payroll/retenues'
      path: '/retenues'
      fullPath: '/payroll/retenues'
      preLoaderRoute: typeof PayrollRetenuesRouteImport
      parentRoute: typeof PayrollRouteRoute
    }
    '/production/': {
      id: '/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/production/articles': {
      id: '/production/articles'
      path: '/articles'
      fullPath: '/production/articles'
      preLoaderRoute: typeof ProductionArticlesRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/production/avancement': {
      id: '/production/avancement'
      path: '/avancement'
      fullPath: '/production/avancement'
      preLoaderRoute: typeof ProductionAvancementRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/production/consommation': {
      id: '/production/consommation'
      path: '/consommation'
      fullPath: '/production/consommation'
      preLoaderRoute: typeof ProductionConsommationRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/production/lots': {
      id: '/production/lots'
      path: '/lots'
      fullPath: '/production/lots'
      preLoaderRoute: typeof ProductionLotsRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/production/operations': {
      id: '/production/operations'
      path: '/operations'
      fullPath: '/production/operations'
      preLoaderRoute: typeof ProductionOperationsRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/production/rejets': {
      id: '/production/rejets'
      path: '/rejets'
      fullPath: '/production/rejets'
      preLoaderRoute: typeof ProductionRejetsRouteImport
      parentRoute: typeof ProductionRouteRoute
    }
    '/reports/couts': {
      id: '/reports/couts'
      path: '/couts'
      fullPath: '/reports/couts'
      preLoaderRoute: typeof ReportsCoutsRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/depenses': {
      id: '/reports/depenses'
      path: '/depenses'
      fullPath: '/reports/depenses'
      preLoaderRoute: typeof ReportsDepensesRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/paie': {
      id: '/reports/paie'
      path: '/paie'
      fullPath: '/reports/paie'
      preLoaderRoute: typeof ReportsPaieRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/production': {
      id: '/reports/production'
      path: '/production'
      fullPath: '/reports/production'
      preLoaderRoute: typeof ReportsProductionRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/productivite': {
      id: '/reports/productivite'
      path: '/productivite'
      fullPath: '/reports/productivite'
      preLoaderRoute: typeof ReportsProductiviteRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/stock': {
      id: '/reports/stock'
      path: '/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof ReportsStockRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/stock/': {
      id: '/stock/'
      path: '/'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/retours': {
      id: '/stock/retours'
      path: '/retours'
      fullPath: '/stock/retours'
      preLoaderRoute: typeof StockRetoursRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/rouleaux-lots': {
      id: '/stock/rouleaux-lots'
      path: '/rouleaux-lots'
      fullPath: '/stock/rouleaux-lots'
      preLoaderRoute: typeof StockRouleauxLotsRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/sorties': {
      id: '/stock/sorties'
      path: '/sorties'
      fullPath: '/stock/sorties'
      preLoaderRoute: typeof StockSortiesRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/valorisation': {
      id: '/stock/valorisation'
      path: '/valorisation'
      fullPath: '/stock/valorisation'
      preLoaderRoute: typeof StockValorisationRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/team/affectations': {
      id: '/team/affectations'
      path: '/affectations'
      fullPath: '/team/affectations'
      preLoaderRoute: typeof TeamAffectationsRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/team/ouvriers': {
      id: '/team/ouvriers'
      path: '/ouvriers'
      fullPath: '/team/ouvriers'
      preLoaderRoute: typeof TeamOuvriersRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/team/travail': {
      id: '/team/travail'
      path: '/travail'
      fullPath: '/team/travail'
      preLoaderRoute: typeof TeamTravailRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/stock/alertes/': {
      id: '/stock/alertes/'
      path: '/alertes'
      fullPath: '/stock/alertes/'
      preLoaderRoute: typeof StockAlertesIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/entrees/': {
      id: '/stock/entrees/'
      path: '/entrees'
      fullPath: '/stock/entrees/'
      preLoaderRoute: typeof StockEntreesIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/inventaire/': {
      id: '/stock/inventaire/'
      path: '/inventaire'
      fullPath: '/stock/inventaire/'
      preLoaderRoute: typeof StockInventaireIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/matieres/': {
      id: '/stock/matieres/'
      path: '/matieres'
      fullPath: '/stock/matieres/'
      preLoaderRoute: typeof StockMatieresIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/matieres/ajouter': {
      id: '/stock/matieres/ajouter'
      path: '/matieres/ajouter'
      fullPath: '/stock/matieres/ajouter'
      preLoaderRoute: typeof StockMatieresAjouterRouteImport
      parentRoute: typeof StockRouteRoute
    }
    '/stock/mouvements/': {
      id: '/stock/mouvements/'
      path: '/mouvements'
      fullPath: '/stock/mouvements/'
      preLoaderRoute: typeof StockMouvementsIndexRouteImport
      parentRoute: typeof StockRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminRolesPermissionsRoute: typeof AdminRolesPermissionsRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminRolesPermissionsRoute: AdminRolesPermissionsRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ExpensesRouteRouteChildren {
  ExpensesCategoriesRoute: typeof ExpensesCategoriesRoute
  ExpensesDepensesRoute: typeof ExpensesDepensesRoute
  ExpensesDepensesRecurrentesRoute: typeof ExpensesDepensesRecurrentesRoute
}

const ExpensesRouteRouteChildren: ExpensesRouteRouteChildren = {
  ExpensesCategoriesRoute: ExpensesCategoriesRoute,
  ExpensesDepensesRoute: ExpensesDepensesRoute,
  ExpensesDepensesRecurrentesRoute: ExpensesDepensesRecurrentesRoute,
}

const ExpensesRouteRouteWithChildren = ExpensesRouteRoute._addFileChildren(
  ExpensesRouteRouteChildren,
)

interface PayrollRouteRouteChildren {
  PayrollAvancesRoute: typeof PayrollAvancesRoute
  PayrollBaremesRoute: typeof PayrollBaremesRoute
  PayrollCalculMensuelRoute: typeof PayrollCalculMensuelRoute
  PayrollCloturesRoute: typeof PayrollCloturesRoute
  PayrollFicheDePaieRoute: typeof PayrollFicheDePaieRoute
  PayrollPrimesRoute: typeof PayrollPrimesRoute
  PayrollRetenuesRoute: typeof PayrollRetenuesRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
}

const PayrollRouteRouteChildren: PayrollRouteRouteChildren = {
  PayrollAvancesRoute: PayrollAvancesRoute,
  PayrollBaremesRoute: PayrollBaremesRoute,
  PayrollCalculMensuelRoute: PayrollCalculMensuelRoute,
  PayrollCloturesRoute: PayrollCloturesRoute,
  PayrollFicheDePaieRoute: PayrollFicheDePaieRoute,
  PayrollPrimesRoute: PayrollPrimesRoute,
  PayrollRetenuesRoute: PayrollRetenuesRoute,
  PayrollIndexRoute: PayrollIndexRoute,
}

const PayrollRouteRouteWithChildren = PayrollRouteRoute._addFileChildren(
  PayrollRouteRouteChildren,
)

interface ProductionRouteRouteChildren {
  ProductionArticlesRoute: typeof ProductionArticlesRoute
  ProductionAvancementRoute: typeof ProductionAvancementRoute
  ProductionConsommationRoute: typeof ProductionConsommationRoute
  ProductionLotsRoute: typeof ProductionLotsRoute
  ProductionOperationsRoute: typeof ProductionOperationsRoute
  ProductionRejetsRoute: typeof ProductionRejetsRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
}

const ProductionRouteRouteChildren: ProductionRouteRouteChildren = {
  ProductionArticlesRoute: ProductionArticlesRoute,
  ProductionAvancementRoute: ProductionAvancementRoute,
  ProductionConsommationRoute: ProductionConsommationRoute,
  ProductionLotsRoute: ProductionLotsRoute,
  ProductionOperationsRoute: ProductionOperationsRoute,
  ProductionRejetsRoute: ProductionRejetsRoute,
  ProductionIndexRoute: ProductionIndexRoute,
}

const ProductionRouteRouteWithChildren = ProductionRouteRoute._addFileChildren(
  ProductionRouteRouteChildren,
)

interface ReportsRouteRouteChildren {
  ReportsCoutsRoute: typeof ReportsCoutsRoute
  ReportsDepensesRoute: typeof ReportsDepensesRoute
  ReportsPaieRoute: typeof ReportsPaieRoute
  ReportsProductionRoute: typeof ReportsProductionRoute
  ReportsProductiviteRoute: typeof ReportsProductiviteRoute
  ReportsStockRoute: typeof ReportsStockRoute
}

const ReportsRouteRouteChildren: ReportsRouteRouteChildren = {
  ReportsCoutsRoute: ReportsCoutsRoute,
  ReportsDepensesRoute: ReportsDepensesRoute,
  ReportsPaieRoute: ReportsPaieRoute,
  ReportsProductionRoute: ReportsProductionRoute,
  ReportsProductiviteRoute: ReportsProductiviteRoute,
  ReportsStockRoute: ReportsStockRoute,
}

const ReportsRouteRouteWithChildren = ReportsRouteRoute._addFileChildren(
  ReportsRouteRouteChildren,
)

interface StockRouteRouteChildren {
  StockRetoursRoute: typeof StockRetoursRoute
  StockRouleauxLotsRoute: typeof StockRouleauxLotsRoute
  StockSortiesRoute: typeof StockSortiesRoute
  StockValorisationRoute: typeof StockValorisationRoute
  StockIndexRoute: typeof StockIndexRoute
  StockMatieresAjouterRoute: typeof StockMatieresAjouterRoute
  StockAlertesIndexRoute: typeof StockAlertesIndexRoute
  StockEntreesIndexRoute: typeof StockEntreesIndexRoute
  StockInventaireIndexRoute: typeof StockInventaireIndexRoute
  StockMatieresIndexRoute: typeof StockMatieresIndexRoute
  StockMouvementsIndexRoute: typeof StockMouvementsIndexRoute
}

const StockRouteRouteChildren: StockRouteRouteChildren = {
  StockRetoursRoute: StockRetoursRoute,
  StockRouleauxLotsRoute: StockRouleauxLotsRoute,
  StockSortiesRoute: StockSortiesRoute,
  StockValorisationRoute: StockValorisationRoute,
  StockIndexRoute: StockIndexRoute,
  StockMatieresAjouterRoute: StockMatieresAjouterRoute,
  StockAlertesIndexRoute: StockAlertesIndexRoute,
  StockEntreesIndexRoute: StockEntreesIndexRoute,
  StockInventaireIndexRoute: StockInventaireIndexRoute,
  StockMatieresIndexRoute: StockMatieresIndexRoute,
  StockMouvementsIndexRoute: StockMouvementsIndexRoute,
}

const StockRouteRouteWithChildren = StockRouteRoute._addFileChildren(
  StockRouteRouteChildren,
)

interface TeamRouteRouteChildren {
  TeamAffectationsRoute: typeof TeamAffectationsRoute
  TeamOuvriersRoute: typeof TeamOuvriersRoute
  TeamTravailRoute: typeof TeamTravailRoute
}

const TeamRouteRouteChildren: TeamRouteRouteChildren = {
  TeamAffectationsRoute: TeamAffectationsRoute,
  TeamOuvriersRoute: TeamOuvriersRoute,
  TeamTravailRoute: TeamTravailRoute,
}

const TeamRouteRouteWithChildren = TeamRouteRoute._addFileChildren(
  TeamRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ExpensesRouteRoute: ExpensesRouteRouteWithChildren,
  PayrollRouteRoute: PayrollRouteRouteWithChildren,
  ProductionRouteRoute: ProductionRouteRouteWithChildren,
  ReportsRouteRoute: ReportsRouteRouteWithChildren,
  StockRouteRoute: StockRouteRouteWithChildren,
  TeamRouteRoute: TeamRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
